import { expect, test } from "playwright/test";
const failureMessage = "Could not archive this case on this device. Nothing was changed. Try again.";
test("an interrupted archive keeps the case active and reports the failure", async ({ page }) => {
  const pageErrors: string[] = []; const externalRequests: string[] = []; page.on("pageerror", e => pageErrors.push(e.message)); page.on("request", r => { const u = new URL(r.url()); if ((u.protocol === "http:" || u.protocol === "https:") && u.hostname !== "127.0.0.1") externalRequests.push(r.url()); });
  await page.goto("/cases-new.html"); await page.locator("#case-title").fill("Archive failure rollback"); await page.locator("#client").fill("Example client"); await page.locator("#amount").fill("5000"); await page.locator("#summary").fill("A synthetic case verifying that interrupted archive writes never hide an active local case."); await page.locator("#continue-button").click(); await page.locator("#continue-button").click(); await page.locator("#local-storage-ack").check(); await page.locator("#continue-button").click(); await page.locator("#open-workspace").click();
  const before = await page.evaluate(async () => { const id = new URLSearchParams(location.search).get("id") as string; const s = await import("/storage.js"); return await s.getCase(id); }); await page.goto("/cases.html"); const card = page.locator(".local-case-card", { hasText: "Archive failure rollback" }); await expect(card).toBeVisible();
  await page.evaluate(() => { const put = IDBObjectStore.prototype.put; let injected = false; IDBObjectStore.prototype.put = function (...args) { const request = put.apply(this, args as [unknown]); if (!injected && this.name === "cases") { injected = true; this.transaction.abort(); } return request; }; }); await card.locator(".archive-case-trigger").click();
  await expect(card.locator(".case-action-status")).toHaveText(failureMessage); await expect(card.locator(".archive-case-trigger")).toHaveText("Archive"); await expect(card.locator(".archived-marker")).toHaveCount(0); await expect(page.locator(".library-view-tabs button[data-view='active'] span")).toHaveText("1"); await expect(page.locator(".library-view-tabs button[data-view='archived'] span")).toHaveText("0");
  const after = await page.evaluate(async () => { const s = await import("/storage.js"); return (await s.getAllCases()).find((r: { title: string }) => r.title === "Archive failure rollback"); }); expect(after.archivedAt).toBeUndefined(); expect(after.updatedAt).toBe(before.updatedAt); await page.reload(); await expect(page.locator(".local-case-card", { hasText: "Archive failure rollback" })).toBeVisible(); expect(externalRequests).toEqual([]); expect(pageErrors).toEqual([]);
});
