import { expect, test } from "playwright/test";

const saveFailure = "The case details could not be saved in this browser. Nothing was changed. Your draft is still open. Try again.";
const conflictFailure = "This case changed in another tab. Close and reopen the editor before saving. Your draft was not saved.";

test("case detail writes preserve drafts and reject stale editors", async ({ page }) => {
  const pageErrors: string[] = []; const externalRequests: string[] = [];
  page.on("pageerror", (error) => pageErrors.push(error.message));
  page.on("request", (request) => { const url = new URL(request.url()); if ((url.protocol === "http:" || url.protocol === "https:") && url.hostname !== "127.0.0.1") externalRequests.push(request.url()); });
  await page.goto("/cases-new.html"); await page.locator("#case-title").fill("Original case title"); await page.locator("#client").fill("Original client"); await page.locator("#amount").fill("USD 5,000"); await page.locator("#summary").fill("An original detailed summary used to verify that failed edits never replace stored case details."); await page.locator("#continue-button").click(); await page.locator("#continue-button").click(); await page.locator("#local-storage-ack").check(); await page.locator("#continue-button").click(); await page.locator("#open-workspace").click();
  const caseId = await page.evaluate(() => new URLSearchParams(location.search).get("id") as string); const before = await page.evaluate(async (id) => (await (await import("/storage.js")).getCase(id)), caseId);
  await page.locator(".case-details-trigger").click(); const dialog = page.locator(".case-details-dialog"); await dialog.locator("#details-title").fill("Draft replacement title"); await dialog.locator("#details-client").fill("Draft replacement client"); await dialog.locator("#details-amount").fill("EUR 4,500"); await dialog.locator("#details-summary").fill("A replacement summary that must remain in the open draft when IndexedDB rejects the write."); await dialog.locator("#details-goal").selectOption("review");
  await page.evaluate(() => { const put = IDBObjectStore.prototype.put; let injected = false; IDBObjectStore.prototype.put = function (...args) { const request = put.apply(this, args as [unknown]); if (!injected && this.name === "cases") { injected = true; this.transaction.abort(); } return request; }; }); await dialog.locator('button[type="submit"]').click();
  await expect(dialog).toBeVisible(); await expect(dialog.locator(".case-details-error")).toHaveText(saveFailure); await expect(dialog.locator("#details-title")).toHaveValue("Draft replacement title"); await expect(dialog.locator("#details-client")).toHaveValue("Draft replacement client"); await expect(dialog.locator("#details-amount")).toHaveValue("EUR 4,500"); await expect(dialog.locator("#details-goal")).toHaveValue("review"); await expect(dialog.locator('button[type="submit"]')).toHaveText("Save changes"); const afterFailure = await page.evaluate(async (id) => (await (await import("/storage.js")).getCase(id)), caseId); expect(afterFailure).toEqual(before); await expect(page.locator("#workspace-title")).toHaveText("Original case title");
  await dialog.locator(".case-details-cancel").click(); await page.reload(); await expect(page.locator("#workspace-title")).toHaveText("Original case title"); await page.locator(".case-details-trigger").click(); await dialog.locator("#details-title").fill("Stale draft title"); const concurrent = await page.evaluate(async (id) => { const s = await import("/storage.js"); const current = await s.getCase(id); const next = { ...current, client: "Concurrent tab client", updatedAt: "2099-01-01T00:00:00.000Z" }; await s.saveCase(next); return next; }, caseId); await dialog.locator('button[type="submit"]').click();
  await expect(dialog).toBeVisible(); await expect(dialog.locator(".case-details-error")).toHaveText(conflictFailure); await expect(dialog.locator("#details-title")).toHaveValue("Stale draft title"); const afterConflict = await page.evaluate(async (id) => (await (await import("/storage.js")).getCase(id)), caseId); expect(afterConflict).toEqual(concurrent); await dialog.locator(".case-details-cancel").click(); await page.reload(); expect(await page.evaluate(async (id) => (await (await import("/storage.js")).getCase(id)).client, caseId)).toBe("Concurrent tab client"); expect(externalRequests).toEqual([]); expect(pageErrors).toEqual([]);
});
