import { expect, test } from "playwright/test";
const imageBytes = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
test("an interrupted permanent deletion preserves the complete case bundle", async ({ page }) => {
  const pageErrors: string[] = []; const externalRequests: string[] = []; page.on("pageerror", e => pageErrors.push(e.message)); page.on("request", r => { const u = new URL(r.url()); if ((u.protocol === "http:" || u.protocol === "https:") && u.hostname !== "127.0.0.1") externalRequests.push(r.url()); });
  await page.goto("/cases-new.html"); await page.locator("#case-title").fill("Deletion failure rollback"); await page.locator("#client").fill("Example client"); await page.locator("#amount").fill("5000"); await page.locator("#summary").fill("A synthetic case verifying that interrupted permanent deletion preserves the complete local case bundle."); await page.locator("#continue-button").click(); await page.locator("#continue-button").click(); await page.locator("#local-storage-ack").check(); await page.locator("#continue-button").click(); await page.locator("#open-workspace").click(); await page.locator("#file-input").setInputFiles({ name: "invoice.png", mimeType: "image/png", buffer: imageBytes });
  const identifiers = await page.evaluate(async () => { const caseId = new URLSearchParams(location.search).get("id") as string; const s = await import("/storage.js"); const [file] = await s.getFilesForCase(caseId); await s.saveFact({ id: "fact_delete_rollback", caseId, type: "other", value: "Invoice total ₹5,000", sourceFileId: file.id, sourceReference: { fileId: file.id, sha256: file.sha256, locator: { kind: "whole_file" } }, status: "confirmed", manuallyEntered: true }); await s.saveSuggestion({ id: "suggestion_delete_rollback", caseId, fileId: file.id, label: "Payment date", value: "3 August", sourceReference: { fileId: file.id, sha256: file.sha256, locator: { kind: "whole_file" } }, status: "suggested" }); await s.saveProcessing({ fileId: file.id, caseId, fileHash: file.sha256, status: "failed", failure: { code: "test", retryable: true } }); await s.saveEvent({ id: "event_delete_rollback", caseId, sourceFileId: file.id, sourceReference: { fileId: file.id, sha256: file.sha256, locator: { kind: "whole_file" } }, type: "note", title: "Invoice received" }); return { caseId }; });
  await page.goto("/cases.html"); const card = page.locator(".local-case-card", { hasText: "Deletion failure rollback" }); await card.locator(".delete-case-trigger").click(); const dialog = page.locator(".case-delete-dialog"); await dialog.locator("#delete-title-confirmation").fill("Deletion failure rollback"); await dialog.locator("#delete-case-ack").check(); await page.evaluate(() => { const remove = IDBObjectStore.prototype.delete; let injected = false; IDBObjectStore.prototype.delete = function (...args) { const request = remove.apply(this, args as [IDBValidKey]); if (!injected && this.name === "cases") { injected = true; this.transaction.abort(); } return request; }; }); await dialog.locator("#confirm-case-delete").click();
  await expect(dialog).toBeVisible(); await expect(dialog.locator("#delete-case-error")).toHaveText("The case could not be deleted. Nothing was changed."); await expect(card).toBeVisible(); const counts = await page.evaluate(async ({ caseId }) => { const s = await import("/storage.js"); return { record: Boolean(await s.getCase(caseId)), files: (await s.getFilesForCase(caseId)).length, facts: (await s.getFactsForCase(caseId)).length, suggestions: (await s.getSuggestionsForCase(caseId)).length, processing: (await s.getProcessingForCase(caseId)).length, events: (await s.getEventsForCase(caseId)).length }; }, identifiers); expect(counts).toEqual({ record: true, files: 1, facts: 1, suggestions: 1, processing: 1, events: 1 }); await dialog.locator(".delete-cancel").click(); await page.reload(); await expect(page.locator(".local-case-card", { hasText: "Deletion failure rollback" })).toBeVisible(); expect(externalRequests).toEqual([]); expect(pageErrors).toEqual([]);
});
