import { expect, test } from "playwright/test";
const failureMessage = "Could not save this change. The previous status is still in place.";
test("an interrupted checklist update restores the prior status and metrics", async ({ page }) => {
  const pageErrors: string[] = []; const externalRequests: string[] = []; page.on("pageerror", e => pageErrors.push(e.message)); page.on("request", r => { const u = new URL(r.url()); if ((u.protocol === "http:" || u.protocol === "https:") && u.hostname !== "127.0.0.1") externalRequests.push(r.url()); });
  await page.goto("/cases-new.html"); await page.locator("#case-title").fill("Checklist storage rollback"); await page.locator("#client").fill("Example client"); await page.locator("#amount").fill("5000"); await page.locator("#summary").fill("A synthetic case verifying that interrupted checklist changes never create misleading collection status."); await page.locator("#continue-button").click(); await page.locator("#continue-button").click(); await page.locator("#local-storage-ack").check(); await page.locator("#continue-button").click(); await page.locator("#open-workspace").click();
  const invoice = page.locator('#workspace-checklist select[data-key="invoice"]'); await expect(invoice).toHaveValue("missing"); await expect(page.locator("#check-progress")).toHaveText("0/6"); const before = await page.evaluate(async () => { const id = new URLSearchParams(location.search).get("id") as string; const s = await import("/storage.js"); return await s.getCase(id); });
  await page.evaluate(() => { const put = IDBObjectStore.prototype.put; let injected = false; IDBObjectStore.prototype.put = function (...args) { const request = put.apply(this, args as [unknown]); if (!injected && this.name === "cases") { injected = true; this.transaction.abort(); } return request; }; });
  await invoice.selectOption("found"); await expect(page.locator(".checklist-save-status")).toHaveText(failureMessage); await expect(invoice).toHaveValue("missing"); await expect(page.locator("#check-progress")).toHaveText("0/6"); await expect(page.locator('.checklist-state-row:has(select[data-key="invoice"])')).toHaveAttribute("data-state", "missing");
  const after = await page.evaluate(async () => { const id = new URLSearchParams(location.search).get("id") as string; const s = await import("/storage.js"); return await s.getCase(id); }); expect(after.updatedAt).toBe(before.updatedAt); expect(after.checklist || []).not.toContain("invoice"); expect(after.checklistStates?.invoice).not.toBe("found"); await page.reload(); await expect(page.locator('#workspace-checklist select[data-key="invoice"]')).toHaveValue("missing"); await expect(page.locator("#check-progress")).toHaveText("0/6"); expect(externalRequests).toEqual([]); expect(pageErrors).toEqual([]);
});
