import { expect, test } from "playwright/test";
const imageBytes = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
const failureMessage = "The fact could not be removed from this device. Nothing was changed. Try again.";
test("an interrupted fact removal preserves the confirmed fact and provenance", async ({ page }) => {
  const pageErrors: string[] = []; const externalRequests: string[] = []; page.on("pageerror", e => pageErrors.push(e.message)); page.on("request", r => { const u = new URL(r.url()); if ((u.protocol === "http:" || u.protocol === "https:") && u.hostname !== "127.0.0.1") externalRequests.push(r.url()); });
  await page.goto("/cases-new.html"); await page.locator("#case-title").fill("Atomic fact removal"); await page.locator("#client").fill("Example client"); await page.locator("#amount").fill("5000"); await page.locator("#summary").fill("A synthetic case verifying that interrupted fact removal preserves confirmed information and provenance."); await page.locator("#continue-button").click(); await page.locator("#continue-button").click(); await page.locator("#local-storage-ack").check(); await page.locator("#continue-button").click(); await page.locator("#open-workspace").click(); await page.locator("#file-input").setInputFiles({ name: "invoice.png", mimeType: "image/png", buffer: imageBytes });
  const before = await page.evaluate(async () => { const caseId = new URLSearchParams(location.search).get("id") as string; const s = await import("/storage.js"); const [file] = await s.getFilesForCase(caseId); await s.saveFact({ id: "fact_atomic_removal", caseId, type: "other", value: "Invoice total ₹5,000", sourceFileId: file.id, sourceReference: { fileId: file.id, sha256: file.sha256, locator: { kind: "whole_file" } }, status: "confirmed", manuallyEntered: true }); return { updatedAt: (await s.getCase(caseId)).updatedAt, hash: file.sha256 }; });
  await page.reload(); const row = page.locator(".fact-record", { hasText: "Invoice total ₹5,000" }); await page.evaluate(() => { const put = IDBObjectStore.prototype.put; let injected = false; IDBObjectStore.prototype.put = function (...args) { const request = put.apply(this, args as [unknown]); if (!injected && this.name === "cases" && this.transaction.objectStoreNames.contains("facts")) { injected = true; this.transaction.abort(); } return request; }; }); await row.locator(".delete-fact").click();
  await expect(page.locator("#upload-message")).toHaveText(failureMessage); await expect(row).toHaveCount(1); const stored = await page.evaluate(async () => { const id = new URLSearchParams(location.search).get("id") as string; const s = await import("/storage.js"); return { facts: await s.getFactsForCase(id), updatedAt: (await s.getCase(id)).updatedAt }; }); expect(stored.facts.map((f: { id: string; sourceReference: { sha256: string } }) => [f.id, f.sourceReference.sha256])).toEqual([["fact_atomic_removal", before.hash]]); expect(stored.updatedAt).toBe(before.updatedAt); await page.reload(); await expect(page.locator(".fact-record", { hasText: "Invoice total ₹5,000" })).toHaveCount(1); expect(externalRequests).toEqual([]); expect(pageErrors).toEqual([]);
});
