import { expect, test } from "playwright/test";
const imageBytes = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=", "base64");
const failureMessage = "The review status could not be changed on this device. Nothing was changed. Try again.";
test("an interrupted not-sure decision preserves the original suggestion status", async ({ page }) => {
  const pageErrors: string[] = []; const externalRequests: string[] = []; page.on("pageerror", e => pageErrors.push(e.message)); page.on("request", r => { const u = new URL(r.url()); if ((u.protocol === "http:" || u.protocol === "https:") && u.hostname !== "127.0.0.1") externalRequests.push(r.url()); });
  await page.goto("/cases-new.html"); await page.locator("#case-title").fill("Atomic uncertain review state"); await page.locator("#client").fill("Example client"); await page.locator("#amount").fill("5000"); await page.locator("#summary").fill("A synthetic case verifying that interrupted review status updates never create misleading UI state."); await page.locator("#continue-button").click(); await page.locator("#continue-button").click(); await page.locator("#local-storage-ack").check(); await page.locator("#continue-button").click(); await page.locator("#open-workspace").click(); await page.locator("#file-input").setInputFiles({ name: "invoice.png", mimeType: "image/png", buffer: imageBytes });
  const before = await page.evaluate(async () => { const caseId = new URLSearchParams(location.search).get("id") as string; const s = await import("/storage.js"); const [file] = await s.getFilesForCase(caseId); await s.saveSuggestion({ id: "suggestion_atomic_uncertain", caseId, fileId: file.id, label: "Invoice total", value: "₹5,000", confidence: 0.55, status: "suggested", sourceReference: { fileId: file.id, sha256: file.sha256, locator: { kind: "quote", quote: "Invoice total ₹5,000" } } }); return { updatedAt: (await s.getCase(caseId)).updatedAt }; });
  await page.reload(); const card = page.locator('.suggestion-card[data-id="suggestion_atomic_uncertain"]'); await page.evaluate(() => { const put = IDBObjectStore.prototype.put; let injected = false; IDBObjectStore.prototype.put = function (...args) { const request = put.apply(this, args as [unknown]); if (!injected && this.name === "cases" && this.transaction.objectStoreNames.contains("suggestions")) { injected = true; this.transaction.abort(); } return request; }; }); await card.locator(".uncertain-suggestion").click();
  await expect(page.locator("#upload-message")).toHaveText(failureMessage); await expect(card.locator(".uncertain-badge")).toHaveCount(0); const stored = await page.evaluate(async () => { const id = new URLSearchParams(location.search).get("id") as string; const s = await import("/storage.js"); return { suggestions: await s.getSuggestionsForCase(id), updatedAt: (await s.getCase(id)).updatedAt }; }); expect(stored.suggestions[0].status).toBe("suggested"); expect(stored.updatedAt).toBe(before.updatedAt); await page.reload(); await expect(page.locator('.suggestion-card[data-id="suggestion_atomic_uncertain"] .uncertain-badge')).toHaveCount(0); expect(externalRequests).toEqual([]); expect(pageErrors).toEqual([]);
});
