import"./storage-health-ui.js";
import{getAllCases,getFilesForCase,getFactsForCase,getSuggestionsForCase,deleteCase}from"./storage.js";
import{summarizeLocalCase,sortLocalCases,filterLocalCases,formatLocalBytes,canConfirmCaseDeletion}from"./case-library-model.js";
const grid=document.querySelector("#case-grid"),empty=document.querySelector("#library-empty"),noResults=document.querySelector("#library-no-results"),controls=document.querySelector("#library-controls"),search=document.querySelector("#case-search");
let items=[],selected=null;
function escape(value=""){const node=document.createElement("span");node.textContent=value;return node.innerHTML}
function relativeDate(value){const time=Date.parse(value);if(!Number.isFinite(time))return"Date unavailable";const days=Math.max(0,Math.floor((Date.now()-time)/86400000));if(days===0)return"Updated today";if(days===1)return"Updated yesterday";if(days<30)return`Updated ${days} days ago`;return`Updated ${new Date(time).toLocaleDateString(undefined,{day:"numeric",month:"short",year:"numeric"})}`}
const dialog=document.createElement("dialog");dialog.className="case-delete-dialog";dialog.innerHTML=`<form id="case-delete-form"><div class="delete-dialog-head"><div><span class="section-label">PERMANENT LOCAL DELETION</span><h2 id="delete-case-title"></h2></div><button type="button" class="dialog-close" aria-label="Close">×</button></div><p id="delete-case-intro"></p><div class="delete-case-summary" id="delete-case-summary"></div><div class="delete-backup-warning" id="delete-backup-warning"></div><label>Type the exact case title to continue<input id="delete-title-confirmation" type="text" autocomplete="off" spellcheck="false"></label><label class="delete-ack"><input id="delete-case-ack" type="checkbox"><span>I understand this permanently removes the case and its original records from this browser.</span></label><p class="delete-case-error" id="delete-case-error" role="status"></p><div class="delete-dialog-actions"><button class="button-secondary delete-cancel" type="button">Cancel</button><button class="danger-button" id="confirm-case-delete" type="submit" disabled>Delete permanently</button></div></form>`;document.body.append(dialog);
const form=dialog.querySelector("form"),titleInput=dialog.querySelector("#delete-title-confirmation"),ack=dialog.querySelector("#delete-case-ack"),confirmButton=dialog.querySelector("#confirm-case-delete"),error=dialog.querySelector("#delete-case-error");
function updateControls(){confirmButton.disabled=!selected||!canConfirmCaseDeletion(selected.record.title||"Untitled case",titleInput.value,ack.checked)}
function closeDialog(){dialog.close();form.reset();selected=null;error.textContent="";confirmButton.disabled=true}
titleInput.addEventListener("input",updateControls);ack.addEventListener("change",updateControls);dialog.querySelector(".dialog-close").onclick=closeDialog;dialog.querySelector(".delete-cancel").onclick=closeDialog;dialog.addEventListener("click",event=>{if(event.target===dialog)closeDialog()});
function updateTotals(){document.querySelector("#library-count").textContent=items.length;document.querySelector("#library-bytes").textContent=formatLocalBytes(items.reduce((sum,item)=>sum+item.totalBytes,0))}
function openDelete(item){selected=item;const title=item.record.title||"Untitled case";dialog.querySelector("#delete-case-title").textContent=`Delete “${title}”?`;dialog.querySelector("#delete-case-intro").textContent="This removes the local case record and all related data in one atomic browser-storage operation.";dialog.querySelector("#delete-case-summary").innerHTML=`<div><strong>${item.fileCount}</strong><span>original records</span></div><div><strong>${item.verifiedFacts}</strong><span>verified facts</span></div><div><strong>${item.pendingReview}</strong><span>to review</span></div><div><strong>${formatLocalBytes(item.totalBytes)}</strong><span>original bytes</span></div>`;const warning=dialog.querySelector("#delete-backup-warning");warning.className=`delete-backup-warning ${item.backup.state}`;warning.textContent=item.backup.state==="current"?"A current encrypted backup is recorded on this device. Confirm you still have the downloaded file and its password.":item.backup.state==="stale"?"Your recorded encrypted backup is out of date. Recent changes may not be recoverable.":"No encrypted backup is recorded for this case. Deletion will not be recoverable through CaseFind.";dialog.showModal();titleInput.focus()}
function render(){const visible=filterLocalCases(items,search.value);empty.hidden=items.length!==0;controls.hidden=items.length===0;noResults.hidden=items.length===0||visible.length!==0;grid.hidden=visible.length===0;grid.innerHTML=visible.map(item=>`<article class="local-case-card"><div class="local-case-top"><span class="status"><i></i>${escape(item.record.status||"collecting")}</span><div class="case-card-signals"><span class="backup-freshness ${item.backup.state}">${escape(item.backup.label)}</span><small>${relativeDate(item.updatedAt)}</small></div></div><h2>${escape(item.record.title||"Untitled case")}</h2><p class="local-client">${escape(item.record.client||"No client entered")}</p><div class="local-case-stats"><div><strong>${item.fileCount}</strong><span>records</span></div><div><strong>${item.verifiedFacts}</strong><span>verified facts</span></div><div><strong>${item.pendingReview}</strong><span>to review</span></div></div><div class="local-case-foot"><span>${formatLocalBytes(item.totalBytes)} stored</span><div><button type="button" class="delete-case-trigger" data-case-id="${escape(item.record.id)}" aria-label="Delete ${escape(item.record.title||"Untitled case")}">Delete</button><a href="case.html?id=${encodeURIComponent(item.record.id)}">Open case <b>→</b></a></div></div></article>`).join("");grid.querySelectorAll(".delete-case-trigger").forEach(button=>button.onclick=()=>openDelete(items.find(item=>item.record.id===button.dataset.caseId)))}
form.onsubmit=async event=>{event.preventDefault();updateControls();if(confirmButton.disabled||!selected)return;confirmButton.disabled=true;confirmButton.textContent="Deleting locally…";error.textContent="";const id=selected.record.id;try{await deleteCase(id);items=items.filter(item=>item.record.id!==id);closeDialog();updateTotals();render()}catch(cause){error.textContent=cause instanceof Error?cause.message:"The case could not be deleted."}finally{confirmButton.textContent="Delete permanently";updateControls()}};
async function load(){try{const records=await getAllCases(),summaries=await Promise.all(records.map(async record=>{const[files,facts,suggestions]=await Promise.all([getFilesForCase(record.id),getFactsForCase(record.id),getSuggestionsForCase(record.id)]);return summarizeLocalCase(record,files,facts,suggestions)}));items=sortLocalCases(summaries);updateTotals();render()}catch{grid.innerHTML='<div class="library-load-error"><h2>We couldn’t open local storage.</h2><p>Check that browser storage is available, then reload this page.</p></div>'}}
search.addEventListener("input",render);load();
