const VERIFIED=new Set(["confirmed","corrected"]),COMPARABLE=new Set(["agreed_price","payment_deadline","delivery_date"]),LABEL_TYPES=new Map([["agreed price","agreed_price"],["payment deadline","payment_deadline"],["delivery date","delivery_date"]]),LABELS={agreed_price:"Agreed price",payment_deadline:"Payment deadline",delivery_date:"Delivery date"};
function clean(value){return String(value??"").trim().replace(/\s+/g," ")}
function keyFor(fact){if(COMPARABLE.has(fact.type))return fact.type;return LABEL_TYPES.get(clean(fact.label).toLowerCase())||null}
function normalize(key,value){let text=clean(value).normalize("NFKC").toLowerCase();if(key==="agreed_price")text=text.replace(/(?<=\d)[,\s](?=\d)/g,"").replace(/\.00$/,".0");return text}
function stableId(key,factIds){let hash=2166136261;for(const char of `${key}|${factIds.join("|")}`){hash^=char.charCodeAt(0);hash=Math.imul(hash,16777619)}return`conflict_${(hash>>>0).toString(16).padStart(8,"0")}`}
function validFact(fact,fileMap){if(!VERIFIED.has(fact.status)||!clean(fact.value))return null;const reference=fact.sourceReference||fact.sourceReferences?.[0],file=fileMap.get(fact.sourceFileId||reference?.fileId);if(!reference||!file||reference.fileId!==file.id||reference.sha256!==file.sha256)return null;const key=keyFor(fact);return key?{fact,key,file,reference,normalized:normalize(key,fact.value)}:null}
function resolutionFor(record,id,factIds){const saved=record.conflictResolutions?.[id];if(!saved||!Array.isArray(saved.factIds)||saved.factIds.join("|")!==factIds.join("|"))return null;if(saved.decision==="selected_fact"&&!factIds.includes(saved.selectedFactId))return null;if(saved.decision!=="selected_fact"&&saved.decision!=="contextual")return null;return saved}
export function detectFactConflicts({record={},files=[],facts=[]}){const fileMap=new Map(files.map(file=>[file.id,file])),groups=new Map;for(const fact of facts){const item=validFact(fact,fileMap);if(!item)continue;if(!groups.has(item.key))groups.set(item.key,[]);groups.get(item.key).push(item)}const conflicts=[];for(const[key,items]of groups){const values=new Set(items.map(item=>item.normalized)),sources=new Set(items.map(item=>item.file.id));if(values.size<2||sources.size<2)continue;const factIds=items.map(item=>String(item.fact.id)).sort(),id=stableId(key,factIds),resolution=resolutionFor(record,id,factIds);conflicts.push({id,key,label:LABELS[key],factIds,items:items.sort((a,b)=>String(a.fact.createdAt||"").localeCompare(String(b.fact.createdAt||""))||String(a.fact.id).localeCompare(String(b.fact.id))).map(item=>({factId:item.fact.id,value:clean(item.fact.value),sourceFileId:item.file.id,sourceName:item.file.name,sourceSha256:item.file.sha256,locator:item.reference.locator||{kind:"whole_file"}})),status:resolution?"resolved":"unresolved",resolution})}return conflicts.sort((a,b)=>a.label.localeCompare(b.label)||a.id.localeCompare(b.id))}
export function saveConflictResolution(record,conflict,input,at=new Date().toISOString()){const decision=String(input.decision||""),selectedFactId=input.selectedFactId?String(input.selectedFactId):null,note=clean(input.note);if(decision!=="selected_fact"&&decision!=="contextual")return{ok:false,error:"Choose how these values should be treated."};if(decision==="selected_fact"&&!conflict.factIds.includes(selectedFactId))return{ok:false,error:"Choose one of the source-linked values."};if(note.length>500)return{ok:false,error:"Resolution note must be 500 characters or fewer."};const resolution={conflictId:conflict.id,factIds:[...conflict.factIds],decision,selectedFactId:decision==="selected_fact"?selectedFactId:null,note,updatedAt:at};return{ok:true,value:{...record,conflictResolutions:{...(record.conflictResolutions||{}),[conflict.id]:resolution},updatedAt:at},resolution}}
export function conflictStats(conflicts){const unresolved=conflicts.filter(item=>item.status==="unresolved").length;return{total:conflicts.length,unresolved,resolved:conflicts.length-unresolved}}
