function validDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const[year,month,day]=value.split("-").map(Number),date=new Date(Date.UTC(year,month-1,day));return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day}
function cleanPage(value){if(value===""||value===null||value===undefined)return null;const page=Number(value);return Number.isInteger(page)&&page>=1&&page<=10000?page:NaN}
export function validateTimelineEvent(input){const value={eventDate:String(input.eventDate||"").trim(),title:String(input.title||"").trim(),description:String(input.description||"").trim(),sourceFileId:String(input.sourceFileId||"").trim(),sourcePage:cleanPage(input.sourcePage),sourceQuote:String(input.sourceQuote||"").trim()};if(!validDate(value.eventDate))return{ok:false,error:"Enter a valid event date."};if(value.title.length<3||value.title.length>120)return{ok:false,error:"Event title must be between 3 and 120 characters."};if(value.description.length>1000)return{ok:false,error:"Event details must be 1,000 characters or fewer."};if(!value.sourceFileId)return{ok:false,error:"Choose the original record that supports this event."};if(Number.isNaN(value.sourcePage))return{ok:false,error:"PDF page must be a whole number between 1 and 10,000."};if(value.sourceQuote.length>500)return{ok:false,error:"Supporting excerpt must be 500 characters or fewer."};return{ok:true,value}}
function sourceReference(file,value){const locator=value.sourcePage?{kind:"pdf_page",page:value.sourcePage}:{kind:"whole_file"};if(value.sourceQuote)locator.quote=value.sourceQuote;return{fileId:file.id,sha256:file.sha256,locator}}
function validateSource(file,value){if(!file||file.id!==value.sourceFileId||!/^([a-f0-9]{64})$/.test(file.sha256||""))return"The selected source record is missing or has no valid SHA-256 hash.";if(value.sourcePage&&file.type!=="application/pdf")return"A page number can only be attached to a PDF source.";return""}
export function createTimelineEvent(caseId,input,file,at=new Date().toISOString(),id=`event_${crypto.randomUUID()}`){const result=validateTimelineEvent(input);if(!result.ok)return result;const sourceError=validateSource(file,result.value);if(sourceError)return{ok:false,error:sourceError};const{sourcePage,sourceQuote,...value}=result.value;return{ok:true,value:{id,caseId,...value,sourceReference:sourceReference(file,result.value),origin:"user_entered",revision:1,createdAt:at,updatedAt:at}}}
export function updateTimelineEvent(existing,input,file,at=new Date().toISOString()){if(!existing?.id||!existing.caseId)return{ok:false,error:"The timeline event is missing or invalid."};const result=validateTimelineEvent(input);if(!result.ok)return result;const sourceError=validateSource(file,result.value);if(sourceError)return{ok:false,error:sourceError};const{sourcePage,sourceQuote,...value}=result.value;return{ok:true,value:{...existing,...value,sourceReference:sourceReference(file,result.value),origin:"user_entered",revision:Number(existing.revision||1)+1,updatedAt:at}}}
export function timelineSourceStatus(event,files){const reference=event?.sourceReference,file=files.find(item=>item.id===(event?.sourceFileId||reference?.fileId));if(!reference||!file)return{ok:false,reason:"missing_source",label:"Source missing",file:null};if(reference.fileId!==file.id||reference.sha256!==file.sha256)return{ok:false,reason:"source_hash_mismatch",label:"Source changed",file};return{ok:true,reason:"valid",label:"Source matched",file}}
export function timelineLocatorLabel(locator={}){if(locator.kind==="pdf_page"&&Number.isInteger(locator.page))return`PDF page ${locator.page}`;return"Whole file"}
export function sortTimelineEvents(events){return[...events].sort((a,b)=>String(a.eventDate).localeCompare(String(b.eventDate))||String(a.createdAt).localeCompare(String(b.createdAt))||String(a.id).localeCompare(String(b.id)))}
